erupt-app:
  # 登录失败几次，需要验证码
  verifyCodeCount: 2
erupt:
  # 是否开启csrf防御
  csrfInspect: true
  # 是否开启redis方式存储session，默认false，开启后需在配置文件中添加redis配置（同 spring boot）
  redisSession: true
  # 附件上传存储路径, 默认路径为：/opt/erupt-attachment
  uploadPath: /Users/itfenbao/Documents/erupt-upload
  # 是否保留上传文件原始名称
  keepUploadFileName: false
  # 登录session时长（redisSession为true时有效）
  upms.expireTimeByLogin: 60
  # 是否记录操作日志，默认true，该功能开启后可在【系统管理 → 操作日志】中查看操作日志
  security.recordOperateLog: true
  # pf4j 配置
  pf4j:
    dev: true
    plugin-location: /Users/itfenbao/Documents/pf4j-plugins
    static-path-pattern: /_p/**

magic-api:
  web: /magic/web
  # 接口配置文件存放路径
  resource.location: erupt/magic-script
  show-url: false

spring:
  redis:
    database: 0
    timeout: 10000
    host: 127.0.0.1
  datasource:
    url: jdbc:mysql://localhost:3306/erupt-example?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: java
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  profiles:
    active: dev
  mail:
    username: xxxx@qq.com
    password: xxxxxxx
    host: smtp.qq.com
    properties:
      mail.smtp.ssl.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.required: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  # 启用 gzip 压缩
  compression:
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
  error:
    includeException: true
    includeStacktrace: ALWAYS
    includeMessage: ALWAYS

springdoc:
  #  pathsToMatch:
  packagesToScan: com.example.demo.controller,xyz.erupt.core
#  swagger-ui:
#    path: /swagger-ui
